### ISSUE TITLE
Certificate Revoked?

### ISSUE THREAD

**Issue by rphauck** [TrakHound/Fanuc-MTConnect-Agent#1]
Recently started getting a UAC message in Windows 10 when trying to start the Configurator. Looks like the certificate was revoked on Jan 21st. I can still run the program through an elevated CMD prompt.

**Comment by PatrickRitchie** [comment]
Yeah we just changed the name of the company from Feenux LLC to TrakHound Inc and are in the middle of updating our certificates. Honestly I didn't know that they would revoke the old certificate before even issuing the new one to us. When we receive the new one I will update the new executables.

**Comment by PatrickRitchie** [comment]
This is fixed as of February 2017

**Comment by laurens777** [comment]
Seems like it is still revoked as I cannot run it.
